FROM python:3.8
WORKDIR /app
COPY requirements.txt ./
RUN apt-get update
RUN apt-get install -y wkhtmltopdf
RUN pip install -r requirements.txt
RUN echo "America/Bogota" > /etc/timezone

CMD [ "python", "bot.py" ]